remote_theme: PfeifferChPT/pc-cdn-template
name: "PC-CDN: COOKIE CONSENT-CONTENT"
title: "COOKIE CONSENT-CONTENT"
subtitle: ""
description: "" #metadescription
markdown: kramdown
highlighter: rouge # pygments or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:year/:month/:day/:title/index.html
excerpt_separator: <!--more-->
templateserverurl: https://template.pc-cdn.de
themecolor: green
themelogo: https://template.pc-cdn.de/assets/img/logo/green_logo.png
dummyimage: overlay-pattern.png
themeURI: none
themeBGimage: 
GallerieDir: 
livereload: true
author: Christian Pfeiffer
since: 2022
# Pagination Settings 
#pagination:
#  enabled: true
#  per_page: 2
#  permalink: '/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true
